# CI builds when PR is created from feature branch to develop
trigger:
- none

pool:
  name: {{poolName}}

variables:
  MajorVersion: 1
  MinorVersion: 0
  PatchVersion: 0
  RevisionVersion: $[counter('revision-counter', 0)]
  buildConfiguration: 'Release'
  project: '{{solutionName}}'

steps:
- task: SonarQubePrepare@7
  displayName: 'SonarQube Prepare'
  inputs:
    SonarQube: 'SonarQube-Rideau-PD'
    scannerMode: 'MSBuild'
    projectKey: '$(project)'
    projectName: '$(project)'
    extraProperties: |
       sonar.cs.vscoveragexml.reportsPaths=$(Agent.TempDirectory)/**/*.coveragexml
       sonar.qualitygate.wait=true

- task: NuGetAuthenticate@1

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/$(project).csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*.sln'
    arguments: '--configuration $(BuildConfiguration) --collect:"Code Coverage"'

- task: PowerShell@2
  displayName: 'Generate Code Coverage Report'
  inputs:
    targetType: 'inline'
    script: |
      $ver = (Get-ChildItem $env:USERPROFILE\.nuget\packages\Microsoft.CodeCoverage | Select-Object -Property Name | Sort-Object -Descending | Select-Object -First 1).Name

      Get-ChildItem -Recurse -Filter "*.coverage" | % {
      $outfile = "$([System.IO.Path]::GetFileNameWithoutExtension($_.FullName)).coveragexml"
      $output = [System.IO.Path]::Combine([System.IO.Path]::GetDirectoryName($_.FullName), $outfile)
      "Analyse '$($_.FullName)' with output '$output'..."
      . $env:USERPROFILE\.nuget\packages\microsoft.codecoverage\$ver\build\netstandard2.0\CodeCoverage\CodeCoverage.exe analyze /output:$output $_.FullName
      }
      "Done"
    workingDirectory: '$(Agent.TempDirectory)'

- task: SonarQubeAnalyze@7
  displayName: 'SonarQube Analyze'

- task: SonarQubePublish@7
  displayName: 'SonarQube Publish'
  inputs:
    pollingTimeoutSec: '300'

- task: sonar-buildbreaker@8
  displayName: 'SonarQube Build Breaker'
  inputs:
    SonarQube: 'SonarQube-Rideau-PD'
